name: Self.Tube
description: "A TubeArchivist Client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  volume_controller: ^3.4.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  dynamic_color: ^1.8.1
  url_launcher: ^6.3.2
  screen_brightness: ^2.1.7
  video_player: ^2.10.1
  wakelock_plus: ^1.4.0
  flutter_linkify: ^6.0.0
  flutter_secure_storage: ^10.0.0
  window_manager: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/appicon.png
    - assets/appicon_filled.png
